apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: devdashboard
spec:
  selector:
    app: devdashboard-backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080  # Pod/Application port

