
apiVersion: v1
kind: Pod
metadata:
  name: devdashboard-frontend
  namespace: devdashboard
spec:
  containers:
  - name: devdashboard-frontend
    image: omkar1232/devdashboard-frontend:latest
    ports:
    - containerPort: 4173

