apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  namespace: devdashboard
  labels:
    app: devdashboard-postgres
spec:
  serviceName: postgres  # Must match the name of the headless service (postgres-service-statefulset.yml)
  replicas: 3
  selector:
    matchLabels:
      app: devdashboard-postgres
  template:
    metadata:
      labels:
        app: devdashboard-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: devdashboard-configmap
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: devdashboard-secrets
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: devdashboard-secrets
                key: POSTGRES_DB
        readinessProbe:
          exec:
            command: ["sh", "-c", "pg_isready -U $(POSTGRES_USER) -d $(POSTGRES_DB)"]
        volumeMounts:
          - name: init
            mountPath: /docker-entrypoint-initdb.d
            readOnly: true
          - name: data
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: init
          configMap:
            name: postgres-init
  volumeClaimTemplates:
    - metadata:
        name: data
        namespace: devdashboard
      spec:
        storageClassName: manual
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi

