# Goal - To run End to End DevSecOps Pipepline

name: DevSecOps

on:
    push:
        branches: [master]

jobs:

    # Code Stage (With Shift Left Approach)
    code-quality:
        uses: ./.github/workflows/code-quality.yml

    # Secret Scanning Stage
    secret-scanning:
        uses: ./.github/workflows/secret-scanning.yml
    
    # Dependency Scanning Stage
    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml

    # Docker Security Scanning Stage
    docker-scan:
        uses: ./.github/workflows/docker-scan.yml
        secrets: inherit

    # dast:
    #     uses: ./.github/workflows/dast.yml
    # sonar-scan:
    #     uses: ./.github/workflows/sonar-scan.yml