# Goal - To run End to End DevSecOps Pipepline

name: DevSecOps

on:
    push:
        branches: [master]

jobs:

    # Code Stage (With Shift Left Approach)
    code-quality:
        uses: ./.github/workflows/code-quality.yml

    # Secret Scanning Stage
    secret-scanning:
        uses: ./.github/workflows/secret-scanning.yml
    
    # Dependency Scanning Stage
    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml

    # Docker Security Scanning Stage
    docker-scan:
        uses: ./.github/workflows/docker-scan.yml
        secrets: inherit

    # SonarQube Scan Stage
    sonar-scan:
        uses: ./.github/workflows/sonar-scan.yml
        secrets: inherit

    # Run Tests
    code-tests:
        uses: ./.github/workflows/code-tests.yml

    # Docker Push Stage
    docker-push:
        needs: [code-quality, secret-scanning, dependency-scan, docker-scan, sonar-scan, code-tests]
        uses: ./.github/workflows/docker-push.yml
        secrets: inherit

    ## ------ CD ------
    deploy:
        needs: docker-push
        uses: ./.github/workflows/deploy.yml
        secrets: inherit

    # DAST Stage
    dast:
        needs: deploy
        uses: ./.github/workflows/dast.yml
        secrets: inherit