# Goal - Ensure the docker files and images are security tested.

name: Docker Scan

on:
    workflow_call:

jobs:
    docker-file-lint-and-scan:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                folders: ['backend','frontend']
        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            - name: ${{ matrix.folders }} Lint Dockerfile
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: ${{ matrix.folders }}/Dockerfile

            - name: Docker Setup [Login]
              uses: docker/login-action@v2
              with:
                username: ${{ vars.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Docker Build ${{ matrix.folders }}
              run: docker build -t ${{ vars.DOCKER_USERNAME }}/devdashboard-${{ matrix.folders }}:latest .
              working-directory: ${{ matrix.folders }}

            - name: Run Trivy Image Vulnerability Scan ${{ matrix.folders }}
              uses: aquasecurity/trivy-action@v0.36.0
              with:
                image-ref: ${{ vars.DOCKER_USERNAME }}/devdashboard-${{ matrix.folders }}:latest
                format: 'table'
                exit-code: '1'
                ignore-unfixed: true
                vuln-type: 'os,library'
                severity: 'CRITICAL'