# To ensure no secrets are committed to the repository, we can use GitHub's secret scanning feature. This workflow will run on every push and pull request to check for any secrets in the codebase.

name: Secret Scanning

on:
    workflow_call:

jobs:
    scan-secrets:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v7
              with:
                fetch-depth: 0  # Fetch all history for all branches and tags

            - name: GitLeaks Scan
              uses: gitleaks/gitleaks-action@v3
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}